name: Gradle Build Test
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 24
        uses: actions/setup-java@v1
        with:
          java-version: 24

      - name: Setup Permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jar
